apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azdo-proxy.fullname" . }}
  labels:
    {{- include "azdo-proxy.labels" . | nindent 4 }}
data:
  config.json: {{ required "Config has to be set." .Values.config | b64enc }}
