name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ "1.14" ]
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: make test
